### ISSUE TITLE
Rules contains Chaos in static text in Rules and Wiki

### ISSUE THREAD

**Issue by erroch** [great-gubal-library/chaos-archives#5]
On the rules page <https://https://crystalarchives.org/rules>
First paragraph under heading "Politics, Religion, and Bigotry" starts "The Chaos roleplay scene is diverse" 

Suggest changing to either "The FFXIV rolepay scene..." or "The Crystal roleplay scene."

On the wiki: 

https://crystalarchives.org/wiki/Archives_Wiki

The welcome page mentioned Chaos in: 
Welcome to the Archives Wiki, a collection of OOC resources about Chaos RP!

**Comment by Maia-Everett** [comment]
Fixed!
